# Generated by Django 3.1.7 on 2021-03-08 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210307_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_owner',
            field=models.CharField(default='Bid Owner', max_length=30),
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bid',
            name='listing_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='closedbid',
            name='closed_bid_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='closedbid',
            name='closed_bid_owner',
            field=models.CharField(default='Bid Owner', max_length=30),
        ),
        migrations.AddField(
            model_name='closedbid',
            name='closed_bid_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='closedbid',
            name='closed_bid_winner',
            field=models.CharField(default='Bid Winner', max_length=30),
        ),
        migrations.AddField(
            model_name='closedbid',
            name='listing_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_content',
            field=models.CharField(default='Comment', max_length=150),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_owner',
            field=models.CharField(default='Comment Owner', max_length=30),
        ),
        migrations.AddField(
            model_name='comment',
            name='listing_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='Category', max_length=45),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='media/auctions/images/default.png', upload_to='media/auctions/images/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.CharField(default='Owner', max_length=30),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default='Title', max_length=60),
        ),
    ]
