# Generated by Django 3.1.7 on 2021-03-08 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210307_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_owner',
            new_name='bid_author',
        ),
        migrations.RenameField(
            model_name='closedbid',
            old_name='closed_bid_owner',
            new_name='closed_bid_author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_owner',
            new_name='comment_author',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='owner',
        ),
        migrations.AddField(
            model_name='listing',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='auctions/images/default.png', upload_to='auctions/images/'),
        ),
    ]
