# Generated by Django 3.1.7 on 2021-03-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210308_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
