# Generated by Django 3.1.7 on 2021-03-09 02:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210308_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bid_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='closedbid',
            name='closed_bid_author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='closed_bid_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_list_listings', models.ManyToManyField(blank=True, related_name='watch_list', to='auctions.Listing')),
                ('watchlist_author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
