# Generated by Django 3.1.7 on 2021-03-09 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210308_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='watchlist_author',
            new_name='watch_list_author',
        ),
    ]
