# Generated by Django 3.1.7 on 2021-03-09 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210308_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watch_list_item',
            field=models.ManyToManyField(blank=True, related_name='watch_list_item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
