# Generated by Django 3.1.7 on 2021-03-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_active_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='active_listing',
            field=models.BooleanField(default=True),
        ),
    ]
